#!/usr/bin/env python

import re
import os
import argparse
import subprocess

if __name__ == '__main__':
    parser = argparse.ArgumentParser('Convert images in path from src format to dst format, optionnaly erase the input')
    parser.add_argument("path")
    parser.add_argument("src")
    parser.add_argument("dst")
    parser.add_argument("--erase", dest='erase', action='store_true')
    parser.set_defaults(erase=False)
    args = parser.parse_args()

    path = args.path
    for f in os.listdir(path):
        if not re.match(".*\.%s" % args.src, f):
            continue

        inp = os.path.join(path, f)
        out = inp.replace(args.src, args.dst)

        subprocess.call(['ffmpeg', '-i', inp, out])
        if args.erase:
            os.remove(inp)

    else:
        raise BaseException("unknown mode")
